// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

void main() {
  final stopwatch = Stopwatch()..start();
  print('Packing and embedding all assets into Dart binary...');

  final assetDirs = [
    Directory('assets/icons'),
    Directory('assets/images'),
    Directory('raw_assets/icons'),
    Directory('raw_assets/images'),
  ];

  final Map<String, String> encodedFiles = {};
  int totalRawBytes = 0;

  for (final dir in assetDirs) {
    if (!dir.existsSync()) continue;
    for (final entity in dir.listSync(recursive: true)) {
      if (entity is File) {
        final path = entity.path.replaceAll('\\', '/');
        // Normalize key to standard asset path (e.g. 'assets/images/dominik1.jpg')
        String key = path;
        if (key.startsWith('raw_assets/')) {
          key = key.replaceFirst('raw_assets/', 'assets/');
        }

        final bytes = entity.readAsBytesSync();
        totalRawBytes += bytes.length;

        // XOR scramble key: "DominikSecretSalt2026"
        const salt = [68, 111, 109, 105, 110, 105, 107, 83, 101, 99, 114, 101, 116, 83, 97, 108, 116, 50, 48, 50, 54];
        final scrambled = List<int>.generate(
          bytes.length,
          (i) => bytes[i] ^ salt[i % salt.length],
        );

        encodedFiles[key] = base64Encode(scrambled);
      }
    }
  }

  print('Found ${encodedFiles.length} asset files (${(totalRawBytes / (1024 * 1024)).toStringAsFixed(2)} MB raw).');

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tools/embed_assets.dart');
  buffer.writeln();
  buffer.writeln("import 'dart:convert';");
  buffer.writeln("import 'dart:typed_data';");
  buffer.writeln("import 'package:flutter/widgets.dart';");
  buffer.writeln();
  buffer.writeln('/// In-memory asset repository for compiled and obfuscated assets.');
  buffer.writeln('class EmbeddedAssets {');
  buffer.writeln('  static const List<int> _salt = [');
  buffer.writeln('    68, 111, 109, 105, 110, 105, 107, 83, 101, 99, 114, 101, 116, 83, 97, 108, 116, 50, 48, 50, 54');
  buffer.writeln('  ];');
  buffer.writeln();
  buffer.writeln('  static final Map<String, Uint8List> _cache = {};');
  buffer.writeln();
  buffer.writeln('  /// Returns raw decrypted bytes for an embedded asset.');
  buffer.writeln('  static Uint8List getBytes(String path) {');
  buffer.writeln('    // Normalize path');
  buffer.writeln("    final cleanPath = path.replaceAll('\\\\', '/');");
  buffer.writeln('    if (_cache.containsKey(cleanPath)) {');
  buffer.writeln('      return _cache[cleanPath]!;');
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    final base64Data = _rawEncodedData[cleanPath];');
  buffer.writeln('    if (base64Data == null) {');
  buffer.writeln("      throw FlutterError('Embedded asset not found: \$path');");
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    final scrambled = base64Decode(base64Data);');
  buffer.writeln('    final decrypted = Uint8List(scrambled.length);');
  buffer.writeln('    for (int i = 0; i < scrambled.length; i++) {');
  buffer.writeln('      decrypted[i] = scrambled[i] ^ _salt[i % _salt.length];');
  buffer.writeln('    }');
  buffer.writeln();
  buffer.writeln('    _cache[cleanPath] = decrypted;');
  buffer.writeln('    return decrypted;');
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln('  /// Returns an ImageProvider backed by in-memory decrypted bytes.');
  buffer.writeln('  static ImageProvider getProvider(String path) {');
  buffer.writeln('    return MemoryImage(getBytes(path));');
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln('  /// Returns an Image widget backed by in-memory decrypted bytes.');
  buffer.writeln('  static Widget getImage(');
  buffer.writeln('    String path, {');
  buffer.writeln('    Key? key,');
  buffer.writeln('    double? width,');
  buffer.writeln('    double? height,');
  buffer.writeln('    BoxFit? fit,');
  buffer.writeln('    Color? color,');
  buffer.writeln('    BlendMode? colorBlendMode,');
  buffer.writeln('    Widget Function(BuildContext, Object, StackTrace?)? errorBuilder,');
  buffer.writeln('  }) {');
  buffer.writeln('    try {');
  buffer.writeln('      return Image.memory(');
  buffer.writeln('        getBytes(path),');
  buffer.writeln('        key: key,');
  buffer.writeln('        width: width,');
  buffer.writeln('        height: height,');
  buffer.writeln('        fit: fit,');
  buffer.writeln('        color: color,');
  buffer.writeln('        colorBlendMode: colorBlendMode,');
  buffer.writeln('        errorBuilder: errorBuilder,');
  buffer.writeln('      );');
  buffer.writeln('    } catch (e, st) {');
  buffer.writeln('      if (errorBuilder != null) {');
  buffer.writeln('        return Builder(builder: (ctx) => errorBuilder(ctx, e, st));');
  buffer.writeln('      }');
  buffer.writeln('      return SizedBox(');
  buffer.writeln('        width: width,');
  buffer.writeln('        height: height,');
  buffer.writeln('      );');
  buffer.writeln('    }');
  buffer.writeln('  }');
  buffer.writeln();
  buffer.writeln('  static const Map<String, String> _rawEncodedData = {');
  for (final entry in encodedFiles.entries) {
    buffer.writeln("    '${entry.key}':");
    buffer.writeln("        '${entry.value}',");
  }
  buffer.writeln('  };');
  buffer.writeln('}');

  final outFile = File('lib/generated/embedded_assets.dart');
  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(buffer.toString());

  print('Generated ${outFile.path} in ${stopwatch.elapsedMilliseconds}ms.');
}
